//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadNeptun.ExampleImplementation.SoapWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessageOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        private System.Guid ExecutionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ExecutionId {
            get {
                return this.ExecutionIdField;
            }
            set {
                if ((this.ExecutionIdField.Equals(value) != true)) {
                    this.ExecutionIdField = value;
                    this.RaisePropertyChanged("ExecutionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeIdOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NodeIdOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapWebservice.HttpComunicationServiceSoap")]
    public interface HttpComunicationServiceSoap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Recieve", ReplyAction="*")]
        MadNeptun.ExampleImplementation.SoapWebservice.RecieveResponse Recieve(MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Recieve", Namespace="http://tempuri.org/", Order=0)]
        public MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequestBody Body;
        
        public RecieveRequest() {
        }
        
        public RecieveRequest(MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecieveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MadNeptun.ExampleImplementation.SoapWebservice.MessageOfString message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MadNeptun.ExampleImplementation.SoapWebservice.NodeIdOfInt32 sender;
        
        public RecieveRequestBody() {
        }
        
        public RecieveRequestBody(MadNeptun.ExampleImplementation.SoapWebservice.MessageOfString message, MadNeptun.ExampleImplementation.SoapWebservice.NodeIdOfInt32 sender) {
            this.message = message;
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecieveResponse", Namespace="http://tempuri.org/", Order=0)]
        public MadNeptun.ExampleImplementation.SoapWebservice.RecieveResponseBody Body;
        
        public RecieveResponse() {
        }
        
        public RecieveResponse(MadNeptun.ExampleImplementation.SoapWebservice.RecieveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RecieveResponseBody {
        
        public RecieveResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HttpComunicationServiceSoapChannel : MadNeptun.ExampleImplementation.SoapWebservice.HttpComunicationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HttpComunicationServiceSoapClient : System.ServiceModel.ClientBase<MadNeptun.ExampleImplementation.SoapWebservice.HttpComunicationServiceSoap>, MadNeptun.ExampleImplementation.SoapWebservice.HttpComunicationServiceSoap {
        
        public HttpComunicationServiceSoapClient() {
        }
        
        public HttpComunicationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HttpComunicationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HttpComunicationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HttpComunicationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MadNeptun.ExampleImplementation.SoapWebservice.RecieveResponse MadNeptun.ExampleImplementation.SoapWebservice.HttpComunicationServiceSoap.Recieve(MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequest request) {
            return base.Channel.Recieve(request);
        }
        
        public void Recieve(MadNeptun.ExampleImplementation.SoapWebservice.MessageOfString message, MadNeptun.ExampleImplementation.SoapWebservice.NodeIdOfInt32 sender) {
            MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequest inValue = new MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequest();
            inValue.Body = new MadNeptun.ExampleImplementation.SoapWebservice.RecieveRequestBody();
            inValue.Body.message = message;
            inValue.Body.sender = sender;
            MadNeptun.ExampleImplementation.SoapWebservice.RecieveResponse retVal = ((MadNeptun.ExampleImplementation.SoapWebservice.HttpComunicationServiceSoap)(this)).Recieve(inValue);
        }
    }
}
