//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadNeptun.ExampleImplementation.SoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapService.ISoapComunicationService")]
    public interface ISoapComunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapComunicationService/Recieve", ReplyAction="http://tempuri.org/ISoapComunicationService/RecieveResponse")]
        void Recieve(MadNeptun.DistributedSystemManager.Core.Objects.NodeId<int> sender, MadNeptun.DistributedSystemManager.Core.Objects.Message<string> message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapComunicationServiceChannel : MadNeptun.ExampleImplementation.SoapService.ISoapComunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapComunicationServiceClient : System.ServiceModel.ClientBase<MadNeptun.ExampleImplementation.SoapService.ISoapComunicationService>, MadNeptun.ExampleImplementation.SoapService.ISoapComunicationService {
        
        public SoapComunicationServiceClient() {
        }
        
        public SoapComunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapComunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapComunicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapComunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Recieve(MadNeptun.DistributedSystemManager.Core.Objects.NodeId<int> sender, MadNeptun.DistributedSystemManager.Core.Objects.Message<string> message) {
            base.Channel.Recieve(sender, message);
        }
    }
}
