//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageOfstring", Namespace="http://schemas.datacontract.org/2004/07/MadNeptun.DistributedSystemManager.Core.O" +
        "bjects")]
    [System.SerializableAttribute()]
    public partial class MessageOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeIdOfint", Namespace="http://schemas.datacontract.org/2004/07/MadNeptun.DistributedSystemManager.Core.O" +
        "bjects")]
    [System.SerializableAttribute()]
    public partial class NodeIdOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ConnectionConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ConnectionConfiguration {
            get {
                return this.ConnectionConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionConfigurationField, value) != true)) {
                    this.ConnectionConfigurationField = value;
                    this.RaisePropertyChanged("ConnectionConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SystemCommunicationService", ConfigurationName="SystemService.ISystemCommunicationService")]
    public interface ISystemCommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemCommunicationService/ISystemCommunicationService/Receive", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/ReceiveResponse")]
        void Receive(MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.MessageOfstring message, MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.NodeIdOfint sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemCommunicationService/ISystemCommunicationService/Init", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/InitResponse")]
        void Init(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemCommunicationService/ISystemCommunicationService/ClearExpiredAlorith" +
            "ms", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/ClearExpiredAlorith" +
            "msResponse")]
        void ClearExpiredAlorithms();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemCommunicationServiceChannel : MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.ISystemCommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemCommunicationServiceClient : System.ServiceModel.ClientBase<MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.ISystemCommunicationService>, MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.ISystemCommunicationService {
        
        public SystemCommunicationServiceClient() {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemCommunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Receive(MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.MessageOfstring message, MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService.NodeIdOfint sender) {
            base.Channel.Receive(message, sender);
        }
        
        public void Init(string message) {
            base.Channel.Init(message);
        }
        
        public void ClearExpiredAlorithms() {
            base.Channel.ClearExpiredAlorithms();
        }
    }
}
