//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace MadNeptun.DistributedSystemManager.AdministratorPanel.SystemService {
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="MessageOfstring", Namespace="http://schemas.datacontract.org/2004/07/MadNeptun.DistributedSystemManager.Core.O" +
        "bjects")]
    [Serializable()]
    public partial class MessageOfstring : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string ValueField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="NodeIdOfint", Namespace="http://schemas.datacontract.org/2004/07/MadNeptun.DistributedSystemManager.Core.O" +
        "bjects")]
    [Serializable()]
    public partial class NodeIdOfint : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private Dictionary<string, string> ConnectionConfigurationField;
        
        [OptionalField()]
        private int IdField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public Dictionary<string, string> ConnectionConfiguration {
            get {
                return this.ConnectionConfigurationField;
            }
            set {
                if ((ReferenceEquals(this.ConnectionConfigurationField, value) != true)) {
                    this.ConnectionConfigurationField = value;
                    this.RaisePropertyChanged("ConnectionConfiguration");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(Namespace="http://SystemCommunicationService", ConfigurationName="SystemService.ISystemCommunicationService")]
    public interface ISystemCommunicationService {
        
        [OperationContract(IsOneWay=true, Action="http://SystemCommunicationService/ISystemCommunicationService/Receive")]
        void Receive(MessageOfstring message, NodeIdOfint sender);
        
        [OperationContract(IsOneWay=true, Action="http://SystemCommunicationService/ISystemCommunicationService/Init")]
        void Init(string message);
        
        [OperationContract(IsOneWay=true, Action="http://SystemCommunicationService/ISystemCommunicationService/ClearExpiredAlorith" +
            "ms")]
        void ClearExpiredAlorithms();
        
        [OperationContract(Action="http://SystemCommunicationService/ISystemCommunicationService/Alive", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/AliveResponse")]
        bool Alive();
        
        [OperationContract(Action="http://SystemCommunicationService/ISystemCommunicationService/Reconfigure", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/ReconfigureResponse" +
            "")]
        void Reconfigure(string[] configuration);
        
        [OperationContract(Action="http://SystemCommunicationService/ISystemCommunicationService/SaveFileOnNode", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/SaveFileOnNodeRespo" +
            "nse")]
        void SaveFileOnNode(string fullPathToSaveFile, byte[] file);
        
        [OperationContract(Action="http://SystemCommunicationService/ISystemCommunicationService/GetConfiguration", ReplyAction="http://SystemCommunicationService/ISystemCommunicationService/GetConfigurationRes" +
            "ponse")]
        string[] GetConfiguration();
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ISystemCommunicationServiceChannel : ISystemCommunicationService, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class SystemCommunicationServiceClient : ClientBase<ISystemCommunicationService>, ISystemCommunicationService {
        
        public SystemCommunicationServiceClient() {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemCommunicationServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemCommunicationServiceClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Receive(MessageOfstring message, NodeIdOfint sender) {
            base.Channel.Receive(message, sender);
        }
        
        public void Init(string message) {
            base.Channel.Init(message);
        }
        
        public void ClearExpiredAlorithms() {
            base.Channel.ClearExpiredAlorithms();
        }
        
        public bool Alive() {
            return base.Channel.Alive();
        }
        
        public void Reconfigure(string[] configuration) {
            base.Channel.Reconfigure(configuration);
        }
        
        public void SaveFileOnNode(string fullPathToSaveFile, byte[] file) {
            base.Channel.SaveFileOnNode(fullPathToSaveFile, file);
        }
        
        public string[] GetConfiguration() {
            return base.Channel.GetConfiguration();
        }
    }
}
